### ISSUE TITLE
Study React

### ISSUE THREAD

**Issue by zainabmelh** [CS3398-Ganymede-Giants/MFP#20]
get familiar with react.js for the next sprint

**Comment by jolaroux** [comment]
There's great explanations and docs on the react site: 
https://reactjs.org/docs/getting-started.html

**Comment by ivyleighp** [comment]
removed from sprint due to time.

**Comment by robtomlinson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Study React](https://trello.com/c/zYtRvqS1/6-study-react)
