### ISSUE TITLE
Set up base Heroku server

### ISSUE THREAD

**Issue by zainabmelh** [CS3398-Ganymede-Giants/MFP#6]
Set up hosting for the site

**Comment by jolaroux** [comment]
Just going to set up a "hello world" that we can all contribute to for this.

**Comment by jolaroux** [comment]
URL is:
https://ganymede18.herokuapp.com/
Basic Node.js server running on Heroku, being served at this very second from the 'testServer' branch of the MFP repo.

Once the web server is a little more full fleshed, I'll push it to master.
